site_name: PyLD
site_description: Python implementation of the JSON-LD API
site_url: https://digitalbazaar.github.io/pyld/
repo_url: https://github.com/digitalbazaar/pyld
repo_name: digitalbazaar/pyld

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - toc:
      permalink: true

plugins:
  - awesome-pages:
      collapse_single_pages: true
  - macros:
      module_name: docs_macros
  - search
